# Generated by Django 4.1.5 on 2023-02-17 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='carnival_date',
            field=models.DateField(default=datetime.date(2023, 2, 21), verbose_name='carnival date'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='carnival_day',
            field=models.BooleanField(default=False, verbose_name='carnival day'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='valentine_date',
            field=models.DateField(default=datetime.date(2023, 2, 14), verbose_name='valentine date'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='valentine_day',
            field=models.BooleanField(default=False, verbose_name='valentine day'),
        ),
    ]
