# Generated by Django 4.1.5 on 2023-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'annonce'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'paramètre'},
        ),
        migrations.AlterModelOptions(
            name='planning',
            options={'verbose_name': 'planning'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'salle'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'enseignant'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'période'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('ABSENCE', 'Absence'), ('REMPLACEMENT', 'Remplacement'), ('RETARD', 'Retard'), ('INFORMATION', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=25),
        ),
    ]
