# Generated by Django 4.1.5 on 2023-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'média',
            },
        ),
    ]
