# Generated by Django 4.1.5 on 2023-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='content',
            new_name='image',
        ),
    ]
