# Generated by Django 4.1.5 on 2023-02-01 05:20

from django.db import migrations, models
import screen.models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_alter_media_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['type'], 'verbose_name': 'annonce'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'salle'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'enseignant'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['rank'], 'verbose_name': 'période'},
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to=screen.models.format_filename),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
