# Generated by Django 4.1.5 on 2023-02-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_alter_announcement_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('RETARD', 'Retard'), ('ABSENCE', 'Absence'), ('REMPLACEMENT', 'Remplacement'), ('INFORMATION', 'Information')], max_length=20),
        ),
    ]
