# Generated by Django 4.1.5 on 2023-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_alter_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(),
        ),
    ]
